//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreBuy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoreBuy.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart/AddToCart.
        /// </summary>
        internal static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.29.239/api/.
        /// </summary>
        internal static string APIPrefix {
            get {
                return ResourceManager.GetString("APIPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cart/DeleteCartItem.
        /// </summary>
        internal static string DeleteCartItem {
            get {
                return ResourceManager.GetString("DeleteCartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/ForgotPassword.
        /// </summary>
        internal static string ForgotPasswordURI {
            get {
                return ResourceManager.GetString("ForgotPasswordURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart/CartItems?UserId=.
        /// </summary>
        internal static string GetCartItems {
            get {
                return ResourceManager.GetString("GetCartItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to itemcategory/getallitemcategories.
        /// </summary>
        internal static string GetCategoryItems {
            get {
                return ResourceManager.GetString("GetCategoryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item/CategoryRelatedItems?CategoryId=.
        /// </summary>
        internal static string GetItemsOfCategory {
            get {
                return ResourceManager.GetString("GetItemsOfCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/GetUserByUserName?UserName=.
        /// </summary>
        internal static string GetUserByUserNameURI {
            get {
                return ResourceManager.GetString("GetUserByUserNameURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemId.
        /// </summary>
        internal static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item/SearchRelatedItems?SearchString=.
        /// </summary>
        internal static string ItemList {
            get {
                return ResourceManager.GetString("ItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/UserLogin.
        /// </summary>
        internal static string LoginURI {
            get {
                return ResourceManager.GetString("LoginURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPassword.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTPReceived.
        /// </summary>
        internal static string OTP {
            get {
                return ResourceManager.GetString("OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/VerifyOTP.
        /// </summary>
        internal static string OTPVerifyURI {
            get {
                return ResourceManager.GetString("OTPVerifyURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPassword.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/ResetPassword.
        /// </summary>
        internal static string ResetPasswordURI {
            get {
                return ResourceManager.GetString("ResetPasswordURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.syncfusion.com/essential-ui-kit-for-xamarin.forms/common/uikitimages/.
        /// </summary>
        internal static string SyncFusion {
            get {
                return ResourceManager.GetString("SyncFusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart/UpdateQuantity.
        /// </summary>
        internal static string UpdateItemQuantity {
            get {
                return ResourceManager.GetString("UpdateItemQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user/UserCheck.
        /// </summary>
        internal static string UserCheck {
            get {
                return ResourceManager.GetString("UserCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        internal static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/UserRegister.
        /// </summary>
        internal static string UserRegisterURI {
            get {
                return ResourceManager.GetString("UserRegisterURI", resourceCulture);
            }
        }
    }
}
